### ISSUE TITLE
Rename/Refactor  class Referral(models.Model):

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/Dr-referral-tracker#17]
class Referral(models.Model):
to
class PatientVisit(models.Model):

The patient is either a Current Patient, Referral field is blank or a New patient, Physician is selected.
Maybe what a selector and table value to indicate new or current.
The relation to a referral Physician is optional.

**Comment by pedro-walter** [comment]
Hi Vincent,

During the weekend, I planned a solution to the issues #15, #16 and #17. I will need to do it in 2-3 phases, with Django migrations between each of them.

== Phase 1 ==

- Rename class Physician to Agent
- Rename class Referral to Patient Visit

I might need to split this phase in two, depending on how Django migrations work.

== Phase 2 == 

- Create Doctor class
- Assign Doctor to PatientVisit (as an optional field in the model, but required in the interface). This will keep the old Referrals intact and searchable, but allowing to link new ones to a Doctor, and even linking old ones to a Doctor too if needed be.

Let me know if this solution fits the needs or if I need to work more on them. I can write down how the Models will look like in the end, if that helps.

**Comment by pedro-walter** [comment]
In a quick test, the django automatic migrations didn't work as expected, so I will need to write the migration manually.

**Comment by vincentdavis** [comment]
@pedro-walter That sounds like a good plan.

**Comment by pedro-walter** [comment]
Resolved by commit https://github.com/Heteroskedastic/Dr-referral-tracker/commit/d4da930e56290c0fc6ac7a0fb2edf99a5ec5aa26.
