### ISSUE TITLE
Fix time zone in referral-history

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/Dr-referral-tracker#24]
Should show local time zone or default US Eastern

**Comment by pprolancer** [comment]
as django support timezone, we should change timezone in settings.py to "US/Eastern".
just we have to change in entire of project to don't us datetime for getting current date/time.
we need to use django timezone as django suggested that.
>>> from django.utils import timezone
>>> now = timezone.now()

**Comment by pprolancer** [comment]
for this issue, if we set TIME_ZONE = 'US/Eastern' all date will be correct automatically.
just here we had an issue for bootstrap-datetimepicker.js becuase that allway calculate dates by UTC.
this enforced me to update that to new version to support timezone.
and also hadn't backward compatibility for this new version.
then this take me some time to migrate that to new version.
