### ISSUE TITLE
Basic test setup.

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/Dr-referral-tracker#27]
- Start adding tests.
- first tests, test issues related to issue #34 
- new user is inactive, changes to user does not make them inactive.
- Make sure they run and work in travis-CI
- Create an issue for each fuction/feature... you are going to make a test.
- Commit message should close issues you create.

**Comment by pprolancer** [comment]
I have written some testcases for other sections of this project.
I am finishing this and I will pull my changes soon.

**Comment by vincentdavis** [comment]
@pprolancer Great!

**Comment by vincentdavis** [comment]
@pedro-walter can your review and merge?
