### ISSUE TITLE
is_active will be changed to false

### ISSUE THREAD

**Issue by pprolancer** [Heteroskedastic/Dr-referral-tracker#34]
When we change any field of user model, that user will be inactive!

**Comment by vincentdavis** [comment]
I think I know why it is like this.
It is still a bug but let me explain what the goal is.
Since the app is public, we don’t what anyone to come along and create an account, login and see the data.
Since we use social auth, A user creates the account and then the admin must activate the account.
The bug is that any time you change anything about a user it makes them inactive.
Understand? I just what to be sure this does not open the app to the public.

**Comment by pprolancer** [comment]
got it. but it is very bad to set is_active to false in this level of model.
we have to do that in registration view. in registration view we can set is_active to false.

**Comment by Shi3A** [comment]
change a save method on User model? or Form clean_data?

**Comment by pprolancer** [comment]
we need to change that in users views.py in registration view.
now I am considering that.

**Comment by Shi3A** [comment]
If you need disabled users by default, just fork user model (create AbstractUser, see docs.djangoproject.org) and set is_active = BooleanFiled(default=False) (something like this)
if you need to disable user when he/admin change a field - re-define a save method.
I thonk that.

**Comment by pprolancer** [comment]
No, this couldn't help us to change default value of is_active to False. because user will be created in create_user function of UserManager and that is specifying is_active to True explicitly.
I found another way to use SOCIAL_AUTH_PIPLINE:
you can see here for more info:
https://groups.google.com/forum/?fromgroups=#!topic/django-social-auth/CfWizuy8STQ

that is working for me.

**Comment by pprolancer** [comment]
now this bug fixed!
as I told, social app has some pipline this can be configurable in settings.
default pipline are here:
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details'
)

I have replaced  'social.pipeline.user.create_user' pipeline with a custom pipeline 'users.models.social_auth_custom_create_user'.

and in this new pipeline I set is_active explicitly to False.

**Comment by cis-yogesh** [comment]
I have done this issue

**Comment by pprolancer** [comment]
@cis-yogesh 
as we talked that is not good to handle that in model signal level. this will reflect on other sections.
then now that is handled this issue in view level instead of model level.
Thanks

**Comment by vincentdavis** [comment]
@pprolancer 
please review the comments Shi3a made on o=your commits.
@cis-yogesh is going to wire some tests for this issue

**Comment by pprolancer** [comment]
Hi @vincentdavis,
I have replied on @Shi3A  comments here: 
https://github.com/Heteroskedastic/Dr-referral-tracker/pull/35

@Shi3A please check my comments and let me know if that is OK. I need to be merge this pull branch asap because I am doing a task which is depended this issue.
Thanks

**Comment by Shi3A** [comment]
I think, all ok, commit.

**Comment by pprolancer** [comment]
@vincentdavis 
can you please merge this pull https://github.com/Heteroskedastic/Dr-referral-tracker/pull/35 ?

**Comment by Shi3A** [comment]
merged
