### ISSUE TITLE
Refactor Physician to ReferringEntity

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/Dr-referral-tracker#46]
ReferringEntity

- organization
- add title
- add timestamp
- physician_name to ReferringEntity_name (I don't care exactly what you call this, re_name is fine, smae with the rest of the fields)
- physician_phone to ReferringEntity_phone
- physician_email to ReferringEntity_email
- referral_special ? How do we deal with predefined Current Patient(not a referral) and Social(no name)

**Comment by pedro-walter** [comment]
Resolved by commit https://github.com/Heteroskedastic/Dr-referral-tracker/commit/42a7bcb1184264b09b8885ba61751f19b5021ce6.
