### ISSUE TITLE
write a plan for single page application

### ISSUE THREAD

**Issue by pprolancer** [Heteroskedastic/Dr-referral-tracker#50]
In single page application better is to use rest api in backend. rest api help us to have a separation between client and server. this help us to dont tie server codes with gui.

after a research I suggest this technologies:

* for client:
.1. angularjs: https://angularjs.org/
.2. a theme called metronic: http://www.keenthemes.com/preview/metronic/
      * admin_1, admin_2 and admin_3 can be good for us

* for server:
.1. django rest api library: we can use one of this libraries:
    * Tastypie: http://tastypieapi.org/
    * Django Rest Framework: http://www.django-rest-framework.org/
.2. JSON as a communication data between client and server.

### useful libraries:
.1 ng-admin: https://github.com/marmelab/ng-admin

### Estimation
* server side: [total: 22 hour]
.1. implement base structure of rest api: [2 h]
.2. implement rest api for all resources: [20 h]:
    * "session" rest api(login/logout/oAuth): [2 h]
    * "user" registration(registration/oAuth): [2 h]
    * "organization" rest api(add/edit/delete/view/list): [3 h]
    * "Referring Entity" rest api(add/edit/delete/view/list): [3 h]
    * "Treating Provider" rest api(add/edit/delete/view/list): [3 h]
    * "Patient Visit" rest api(add/edit/delete/view/list): [3 h]
    * "Patient Visit History Report" rest api(view): [2 h]
    * "Patient Visits Report" rest api(view): [2 h]

* client side: [total: 43 hour]
.1. design and implement base structure of ui: [5 h]
.2. implement base structure of angular: [4 h]
.3. design and implement pages: [34 hour]
    * login page(login/oAuth): [2 h]
    * user registeration page(register/oAuth): [3 h]
    * dashboard(home) page: [5 h]
    * "organization" page(add/edit/delete/view/list): [5 h]
    * "Referring Entity" page(add/edit/delete/view/list): [5 h]
    * "Treating Provider" page(add/edit/delete/view/list): [5 h]
    * "Patient Visit" page(add/edit/delete/view/list): [5 h]
    * "Patient Visit History Report" page(view): [2 h]
    * "Patient Visits Report" page(view): [2 h]

**Comment by pprolancer** [comment]
@vincentdavis 
please take a look at this task. I have finished my research and I have written the result here.

**Comment by vincentdavis** [comment]
@pprolancer Well done!
1) Question, Would the frontend Angularjs be is a different repo?
2) What is the least you can do to give a demonstration?

**Comment by pprolancer** [comment]
@vincentdavis 
1) maybe yes, but for now we can add a subdir in static page called ui2 and put all files here.
2) we can do just this steps for least requirements to show a demo:
* server side: [total: 5 hour]

.1. implement base structure of rest api: [2 h]
.2. implement rest api for all resources:
    * "organization" rest api(add/edit/delete/view/list): [3 h]
* client side: [total: 14 hour]

.1. design and implement base structure of ui: [5 h]
.2. implement base structure of angular: [4 h]
.3. design and implement pages:
    * "organization" page(add/edit/delete/view/list): [5 h]

**Comment by vincentdavis** [comment]
@pprolancer Lets start to implements the basics. Please create a milestone and issues for the steps. Assign frontend issues to yourself and @kushaw. Assign backend issues to yourself or @pedro-walter.
Always have someone review pull requests before commit.
