### ISSUE TITLE
Inputting a new Patient Visit on the same day creates a duplicate

### ISSUE THREAD

**Issue by pedro-walter** [Heteroskedastic/Dr-referral-tracker#51]
I believe it should instead sum the referrals:
![snapshot2](https://cloud.githubusercontent.com/assets/5803022/13721384/15bbcfd6-e804-11e5-9439-901d915e3e02.png)

**Comment by vincentdavis** [comment]
This is correct. This view is so that the person doing the data entry can see what they have entered. Basically this is an entry log.

**Comment by vincentdavis** [comment]
working as expected.
