### ISSUE TITLE
Add Clinic level to app.

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/Dr-referral-tracker#59]
Add a new level, "Clinic" All users, Organizations, Referring-Entity, visits, treating-Practitioners are separate for each clinic.
A Clinic can have multiple users.

What do we do with URL's Should we get a domain?

Users do not have access to /admin.
/Admin will be only for developers.

**Comment by pedro-walter** [comment]
A clinic may have multiple users, but a user is only associated to one clinic, right?

Also, creating a regular user will not enable him/her to access admin, only superusers (created via manage.py).

**Comment by vincentdavis** [comment]
Yes

**Comment by pedro-walter** [comment]
Should Clinic become a subclass of TrackedModel? (that means tracking the creation/modification date)

**Comment by vincentdavis** [comment]
@pedro-walter TrackedModel, yes. in part because at some point I will be charging for access to the service.

**Comment by pedro-walter** [comment]
Sorry for taking so long. We will need to be careful on the migration, but we should be fine.
