### ISSUE TITLE
3 testcase failing after design new models

### ISSUE THREAD

**Issue by pprolancer** [Heteroskedastic/Dr-referral-tracker#63]
Hi @pedro-walter 
we have 3 testcase failing here in latest codes after designed new modes.
please consider them.
Thanks

> Creating test database for alias 'default'...
> 
> ......F......F...F.....
> 
> ======================================================================
> FAIL: test_edit (tracking.tests.test_views.EditOrganizationViewTest)
> quantifiedcode: ignore it!
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/ali/work/freelancing/vincent/Dr-referral-tracker/tracking/tests/test_views.py", line 273, in test_edit
>     self.assertEqual(organization.org_name, data['org_name'])
> AssertionError: 'phys1' != 'new_name'
> - phys1
> + new_name
> 
> 
> ======================================================================
> FAIL: test_post_orgform (tracking.tests.test_views.IndexViewTest)
> quantifiedcode: ignore it!
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/ali/work/freelancing/vincent/Dr-referral-tracker/tracking/tests/test_views.py", line 99, in test_post_orgform
>     self.assertEqual(response.status_code, 302)
> AssertionError: 200 != 302
> 
> ======================================================================
> FAIL: test_add_post_form (tracking.tests.test_views.PatientVisitViewTest)
> quantifiedcode: ignore it!
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/ali/work/freelancing/vincent/Dr-referral-tracker/tracking/tests/test_views.py", line 153, in test_add_post_form
>     self.assertEqual(response.status_code, 302)
> AssertionError: 200 != 302
> 
> ----------------------------------------------------------------------
> Ran 23 tests in 2.423s
> 
> FAILED (failures=3)
>

**Comment by vincentdavis** [comment]
@pedro-walter I should have caught this, please make sure travis-ci passes before merging in the future.
