### ISSUE TITLE
Time tracking optional by user.

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/Dr-referral-tracker#73]
User wants the time tracking "appointment time" and "Actual time" to be a optional part of the visit form. The field is optional but the user does not want them displayed as part of the form (per user). What is the best way to do this?

**Comment by pprolancer** [comment]
@vincentdavis 
is this possible to explain more?

**Comment by vincentdavis** [comment]
@pedro-walter can you review this and merge.
