### ISSUE TITLE
design and implement base structure of ui

### ISSUE THREAD

**Issue by pprolancer** [Heteroskedastic/Dr-referral-tracker#82]
as you know we want to implement new ui2 by angularjs.
ui should be designed by a metronic theme: http://www.keenthemes.com/preview/metronic/theme/admin_2_angularjs/

@kushaw, please let me know if any question.

**Comment by pprolancer** [comment]
@kushaw, you can find source of metronic theme from here: https://github.com/mikesmayer/metronic

you need to refine and polish this theme.
please ping me everytime you want to start this task.

**Comment by pprolancer** [comment]
@kushaw 
I have created a separated directory in Angular-version branch called ui2.
you can see that here:
https://github.com/Heteroskedastic/Dr-referral-tracker/tree/Angular-version/static
in this "static" dir you have ui2 directory. then you should implement all angular application there in ui2. any new required libraries can be added in /static/js/ and any required css can be added in /static/css/ and any required fonts can be added in /static/fonts/ .
I have added some initial files there in ui2.

**Comment by pprolancer** [comment]
@kushaw, this is a wireframe for base structure of ui.
![image](https://cloud.githubusercontent.com/assets/13080577/14228012/06a175b0-f91f-11e5-925e-1818047f703b.png)

**Comment by kushaw** [comment]
do we need to create this page from scratch or use the Matroni's angular theme from the UI(https://github.com/mikesmayer/metronic/ ......theme/templates/admin/angularjs/index.html) or we just need to create the body part as suggested in the above comment (wire-frame img)

**Comment by pprolancer** [comment]
@kushaw 
the base structure of our page is "metronic" theme page(http://www.keenthemes.com/preview/metronic/theme/admin_2_angularjs/).
you should polish that page to be look like wireframe. indeed wireframe show you which component in metronic theme is required and which components should be dropped.

**Comment by kushaw** [comment]
![org](https://cloud.githubusercontent.com/assets/11432527/14293634/1277b098-fb8b-11e5-9705-264a371242a3.png)

I had polished the UI and will commit ti tomorrow. after i complete the organization body part. and connect it with the "http://162.243.91.30/api/v1/organization/"

if i am going wrong any where please let me know.

**Comment by pprolancer** [comment]
great @kushaw 
just FYI, we have merged Angular-version branch with master. then please do that steps but using master branch instead of Angular-version branch. now we work with master branch only.

**Comment by kushaw** [comment]
I had committed issue No 82, however i am getting an error on the click of edit button check the attachment, can you check this if you have time i tried it a lot but could not crack. however trying to fix... for some reasons I had used the hard coded JSON for OrganizationsController.js I will change that.

![debug](https://cloud.githubusercontent.com/assets/11432527/14374193/686a9dbc-fd70-11e5-963b-2516d48e2872.png)
