### ISSUE TITLE
design and implement pages(add/edit/delete/list) for "organization"

### ISSUE THREAD

**Issue by pprolancer** [Heteroskedastic/Dr-referral-tracker#83]
after designed and implemented base of ui by angular, we need to implement pages for first resource called "organization".
I have attached current(old) ui pages of organization to have idea about fields.
![image](https://cloud.githubusercontent.com/assets/13080577/14224766/2088a6b8-f8bd-11e5-910a-a0c12cbd3f63.png)
![image](https://cloud.githubusercontent.com/assets/13080577/14224767/30566f80-f8bd-11e5-88b8-f456ed49996c.png)

**Comment by pprolancer** [comment]
@kushaw 
we are using django-rest-framework to implement rest api for resources.
then if you setup the project on your pc and run that locally, you can see the spec of all api in this url:
http://localhost:8000/api/v1/

and so you can find organization rest api here:
http://localhost:8000/api/v1/organization/

please let me know if any question.

**Comment by kushaw** [comment]
I would need help in setting up this application on my Local machine. I would also what to have a walk through of the project. 
on the below points:

- project description.
- what is pending.
- what is the project architecture. 
- if it is Metronic UI are we using this page with all its code css and js?
![angular](https://cloud.githubusercontent.com/assets/11432527/14255313/1469f634-fab1-11e5-8ead-2095a2b932c2.png)

**Comment by vincentdavis** [comment]
@kushaw The anaconda installation of Python is a great way to get Python on you Windows machine.
choose the python 3.5
https://bitnami.com/stack/django/installer

What are you using to edit files? What IDE or text editor?

From here is is easy to run a development version of the app from your Windows machine. I or @pprolancer  can probably walk you through the other steps.

**Comment by pprolancer** [comment]
@kushaw 
1- as a first priority task, better is to install dr referral project locally. you have this choice:
a) as vincent told, you can use anaconda
b) or you can install everything directly in windows(postgresql + python libs).
c) or you can create a virtual machine via virtualbox(or vmware) and install ubuntu on that.

2- regarding project architecture, for now you only need to know we want to implement a single page application via:
a) REST api
b) JSON
c) Angularjs
you can see REST api spec here as I sent in skype: http://162.243.91.30/api/v1/

3- for start we want to polish metronic theme to create base structure of our ui.
then regarding js and css of metronic theme, you need to hold least libraries to could design base structure of ui + organization page as you see in wireframe in issue #82 .
then we can add new libraries in future if needed.
just again, remember our base ui should be according our metronic theme + wireframe.
then you dont need to design everything from scratch. design is according metronic theme, just you need to polish that to be fit of our work.

Thanks

**Comment by kushaw** [comment]
thanks Ali it clear now
