### ISSUE TITLE
simple issue to learn pull request

### ISSUE THREAD

**Issue by pprolancer** [Heteroskedastic/Dr-referral-tracker#85]
@kushaw 
this is a simple issue to learn you how to apply your changes via pull request in github.
for this issue please add "fontawesome" library in our files and link that in /static/ui2/index.html

this is steps:
1- got to https://github.com/Heteroskedastic/Dr-referral-tracker and make a fork from this repository to your account. (just push "Fork" button in right-top corner)
2- in your pc clone from your repository by this command: git clone https://github.com/kushaw/Dr-referral-tracker
3- git checkout Angular-version
4- git checkout -b issue#85
5- add fontawesome library to our directory in static
6- commit your changes
7- git push kushaw issue#85
8- go to https://github.com/kushaw/Dr-referral-tracker and select issue#85 branch.
9- push "new pull request" button
10- select "Angular-version" from "base" branch

let me know if any question.

**Comment by kushaw** [comment]
I could successfully complete this thanks Ali. Please check and if all right please close this issue.
